# Generated by Django 5.2.1 on 2025-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='器具名')),
                ('manufacture_name', models.CharField(max_length=255, verbose_name='メーカー名')),
                ('model_number', models.CharField(max_length=255, verbose_name='型番')),
                ('image', models.ImageField(upload_to='appliances/', verbose_name='器具画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '器具',
                'verbose_name_plural': '器具一覧',
            },
        ),
    ]
