services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000:8000
    volumes:
      - ./src:/code
    env_file:
      - .env.django
    depends_on:
      - db
      
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.db
      
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    depends_on:
      - django

volumes:
  postgres-data: