# Generated by Django 5.2.1 on 2025-05-18 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ボタン名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ボタン',
                'verbose_name_plural': 'ボタン一覧',
            },
        ),
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_id', models.IntegerField(verbose_name='関節ID')),
                ('degree', models.IntegerField(verbose_name='角度')),
                ('speed', models.IntegerField(verbose_name='速度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angles', to='buttons.button', verbose_name='ボタン')),
            ],
            options={
                'verbose_name': 'ボタンの角度',
                'verbose_name_plural': 'ボタンの角度一覧',
            },
        ),
    ]
