# Generated by Django 5.2.1 on 2025-05-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_appliance_user'),
        ('buttons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='appliance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='appliances.appliance', verbose_name='器具'),
            preserve_default=False,
        ),
    ]
